### ISSUE TITLE
Unable to launch it in the iOS - XCode simulator

### ISSUE THREAD

**Issue by smangalath** [mlaval/angular2-react-native-seed#2]
Running gulp start.ios fails on launch ios

No devices are booted.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/ngRnSeed.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

```
at ChildProcess.exithandler (child_process.js:207:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Socket.<anonymous> (internal/child_process.js:323:11)
at emitOne (events.js:96:13)
at Socket.emit (events.js:188:7)
at Pipe._handle.close [as _onclose] (net.js:492:12)
```

  killed: false,
  code: 1,
  signal: null,
  cmd: 'react-native run-ios' }
[19:14:48] Finished '!launch.ios' after 33 s

**Comment by mlaval** [comment]
I just did a clean install and was able to start the application without any problems.

If this is still reproducible, can you please provide more details about your environment?

**Comment by mlaval** [comment]
Please re-open with more details if this is still occurring.
